### ISSUE TITLE
[BUG] There is a version that we cannot get.

### ISSUE THREAD

**Issue by m3y** [karancode/kustomize-github-action#22]
**Describe the bug**
Only the following versions of kustomize are not available
- v3.2.1
- v3.2.2
- v3.2.3

**To Reproduce**
```
name: 'Kustomize GitHub Actions'
on:
  - pull_request
jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@v1.1.0
        with:
          kustomize_version: '3.2.3'
          kustomize_build_dir: '.'
          kustomize_comment: true
          kustomize_output_file: "gitops/rendered.yaml"
          enable_alpha_plugins: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
kustomize is available for download

**Running on:**
- OS: ubuntu-latest
- Version: @v1.1.0

**Additional context**
There are three patterns of kustomize download URLs 😵 
Before 3.2.0
```
https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
```
3.3.0 and later
```
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.3.0/kustomize_v3.3.0_linux_amd64.tar.gz
```
3.2.1 to 3.2.3 😞 
```
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.2.3/kustomize_kustomize.v3.2.3_linux_amd64
```
```
```
