### ISSUE TITLE
[BUG] Failed to recognize http resources 

### ISSUE THREAD

**Issue by mcoletti** [karancode/kustomize-github-action#30]
**Describe the bug**
Failed to pull down http resources that are defined in the kustomization.yaml spec

**To Reproduce**
Create a Kustomization.yaml spec with the below definition:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.1/manifests/ha/install.yaml

```

**Expected behavior**
Kustomize should be able to pull down remote http resource that are defined

**Screenshots/Actions log**

build: error: failed to execute kustomize build in argo/deploy/overlays/chg-platform-shared-svc-prod.
Error: accumulating resources: recursed accumulation of path '../../base': accumulating resources: accumulating resources from 'https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.1/manifests/ha/install.yaml': evalsymlink failure on '/github/workspace/argo/deploy/base/https:/raw.githubusercontent.com/argoproj/argo-cd/v2.0.1/manifests/ha/install.yaml' : lstat /github/workspace/argo/deploy/base/https:: no such file or directory

**Running on:**

**Additional context**
This works locally on my system.
