### ISSUE TITLE
[BUG] v1.3.0 gets stuck waiting forever for kustomize download url

### ISSUE THREAD

**Issue by nfoucha** [karancode/kustomize-github-action#38]
**Describe the bug**

As of v1.3.0, it looks like the API throttling issue has gone the opposite direction.  Where before the action would fail, it now runs forever.

**To Reproduce**

Run a GitHub actions workflow with some number of kustomize steps (on this specific build it's 9 parallel steps)

**Expected behavior**

The action should complete normally with some delay due to API throttling.

**Screenshots/Actions log**

![image](https://user-images.githubusercontent.com/73838612/209206962-61fe13c9-6752-43e8-916d-229f1021790d.png)
> getting download url for kustomize 4.2.0

**Running on:**

 - OS: 20.04.5
 - Version @v1.3.0
 - Kustomize Version 4.2.0
 - Kustomize build options: `--load-restrictor LoadRestrictionsNone`

**Additional context**

As with the original issue #35 this is intermittent in nature.  Rerunning the failed steps eventually works.  Subsequent runs may fail different kustomize steps.

With the code in the PR that addressed the initial issue, I would expect a hard failure after ~120s.  That's not happening here as the action was still running after 25 minutes.

**Comment by ekristen** [comment]
I'm seeing this behavior a LOT. Like multiple times a day.

**Comment by karancode** [comment]
@nfoucha could you try with latest version `@master` or  [v1.3.1](https://github.com/karancode/kustomize-github-action/releases/tag/v1.3.1) ? Thanks to @ekristen's contrib.

**Comment by nfoucha** [comment]
I unfortunately left the company where I was encountering this issue.  @cwhite-ecr can you take a look?

**Comment by cwhite-ecr** [comment]
@karancode @nfoucha, I set up `v1.3.1` against the workflow reported against in this issue and have not run into any limiting since doing so.

**Comment by okkero** [comment]
Hi. I'm still experiencing this regularly on `master`. Even in the cases where it doesn't hang forever, it still takes a minute or two to get the Kustomize download URL.

**Comment by byted** [comment]
same for us. On `master` we get stuck regularly.

**Comment by ekristen** [comment]
@byted if you add authentication based on the docs it should resolve it.

**Comment by davidwincent** [comment]
Seeing 2 minutes plus on step "getting download url for kustomize 5.0.0"

Workflow file:
```yaml
name: "Validate dev"
on:
  pull_request:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kustomize-argocd:
    name: "Kustomize deploy/overlays/dev/argocd"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Dry run"
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_install: true
          kustomize_version: "5.0.0"
          kustomize_build_dir: "deploy/overlays/dev/argocd"
          kustomize_comment: true
          kustomize_output_file: "gitops/overlays/dev/argocd/rendered.yaml"
        env:
          GITHUB_ACCESS_TOKEN: ${{ env.GITHUB_TOKEN }}

```

**Comment by davidwincent** [comment]
> Seeing 2 minutes plus on step "getting download url for kustomize 5.0.0"
> 
> Workflow file:
> 
> ```yaml
> name: "Validate dev"
> on:
>   pull_request:
>     branches:
>       - main
> env:
>   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> 
> jobs:
>   kustomize-argocd:
>     name: "Kustomize deploy/overlays/dev/argocd"
>     runs-on: ubuntu-latest
>     steps:
>       - name: "Checkout"
>         uses: actions/checkout@master
> 
>       - name: "Dry run"
>         uses: karancode/kustomize-github-action@master
>         with:
>           kustomize_install: true
>           kustomize_version: "5.0.0"
>           kustomize_build_dir: "deploy/overlays/dev/argocd"
>           kustomize_comment: true
>           kustomize_output_file: "gitops/overlays/dev/argocd/rendered.yaml"
>         env:
>           GITHUB_ACCESS_TOKEN: ${{ env.GITHUB_TOKEN }}
> ```

Changing workflow to this worked for me:

```yaml
name: "Validate dev"
on:
  pull_request:
    branches:
      - main

jobs:
  kustomize-argocd:
    name: "Kustomize deploy/overlays/dev/argocd"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Dry run"
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_install: true
          kustomize_version: "5.0.0"
          kustomize_build_dir: "deploy/overlays/dev/argocd"
          kustomize_comment: false
          kustomize_output_file: "itops/overlays/dev/argocd/rendered.yaml"
          token: ${{ secrets.GITHUB_TOKEN }}

```
