### ISSUE TITLE
[BUG] Pulls Docker Image Before Any Defined Steps

### ISSUE THREAD

**Issue by john-yacuta-submittable** [karancode/kustomize-github-action#43]
**Describe the bug**

Why does this GitHub Action pull a Docker image before any actual defined steps in the workflow? 

Its doing a pre-step of `Build karancode/kustomize-github-action@master` before my defined step of `Checkout` in my workflow.

**To Reproduce**

Run the workflow as usual and you will see the execution of the pre-step running before any actual steps.

**Expected behavior**

Only pull the Docker image in the exact step that I defined in the workflow. I am trying to authenticate with Docker Hub so the pull rate limit can be increased but the pre-step mentioned above is running first so its not logging in first. 

**Screenshots/Actions log**

Snippet of the workflow im running:

```yaml
jobs:
  test:
    name: Run Kubernetes Validation
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

   # ...

    - name: Run Kustomize Build Validation
      uses: karancode/kustomize-github-action@master
      with:
        kustomize_version: '3.0.0'
        kustomize_build_dir: 'kustomize'
        kustomize_build_options: "--load_restrictor none"
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
```

Notice in the below screenshot that there are steps of building a kustomize Docker image BEFORE the `Checkout` step runs and then following the `Login to Docker Hub` step, etc.. 

<img width="427" alt="Screenshot 2023-02-24 at 8 44 11 AM" src="https://user-images.githubusercontent.com/104800617/221259462-cbaa1ed3-b603-4281-abba-2ddddb4e6a38.png">

**Running on:**

OS: ubuntu-latest

**Additional context**
