### ISSUE TITLE
[BUG] Kustomize build invalid format for kustomize_build_output when using runner v2.306.0

### ISSUE THREAD

**Issue by JulesLalu** [karancode/kustomize-github-action#45]
**Describe the bug**
Since the github runner was upgraded to v2.306.0, our kustomize-github-action fails with invalid format for the kustomize_build_output. This could be linked to the merging of following PR on the github runner repository : https://github.com/actions/runner/pull/2627
I assume the way to solve this would be to update the job to follow Github Action multiline string convention : https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

**To Reproduce**
I haven't had the occasion to try the job with different kustomize build outputs, so it's hard to know if our workflow being broken is linked to the content of the output. 
Parameters used are
```
with:
    kustomize_version: 4.5.2
    kustomize_build_dir: ${kustomize_dir}
    kustomize_comment: true
    kustomize_install: 1
    enable_alpha_plugins: 0
  env:
    TF_VAR_github_token: ***
```

**Expected behavior**
The kustomize output is correctly handled, and the workflow succeeds. 

**Screenshots/Actions log**
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'kustomize_build_output=...
```

Thanks in advance for your help !
